name: Build and Release FoundryVTT Module

on:
  push:
    tags:
      - "v*.*.*"   # wird ausgelöst, wenn du ein Tag pushst wie v1.0.5

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Extract tag version
        id: tag
        run: |
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}   # remove leading 'v'
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update module.json with version and download URL
        run: |
          VERSION=${{ steps.tag.outputs.version }}
          DOWNLOAD_URL="https://github.com/${GITHUB_REPOSITORY}/releases/download/v$VERSION/sea-of-monsters.zip"
          
          # Update version
          jq --arg v "$VERSION" '.version=$v' module.json > module.tmp.json
          mv module.tmp.json module.json
          
          # Update download
          jq --arg url "$DOWNLOAD_URL" '.download=$url' module.json > module.tmp.json
          mv module.tmp.json module.json
          
          cat module.json  # zum Debuggen

      - name: Prepare ZIP folder
        run: |
          mkdir -p dist
          mkdir -p package/sea-of-monsters
          cp -r module.json lang package/sea-of-monsters/
          cd package
          zip -r "../dist/sea-of-monsters.zip" sea-of-monsters
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/sea-of-monsters.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
